stuff

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -32,7 +32,22 @@ set -e
 a() { sed 's/^/-----> /'; }
 i() { sed 's/^/       /'; }
 
-url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz-doc_2.38.0-10_all.deb'
+case "$STACK" in
+  cedar-14)
+    echo "Installing Graphviz version 2.36.0" | a
+    echo "(Ubuntu package graphviz_2.36.0-0ubuntu3.1_amd64.deb)" | i
+    # URL can be found out with: apt-cache show graphviz | grep Filename
+    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.36.0-0ubuntu3.1_amd64.deb' ;;
+  cedar)
+    echo "Installing Graphviz version 2.20.2" | a
+    echo "(Ubuntu package graphviz_2.20.2-8ubuntu3.2_amd64.deb)" | i
+    # URL can be found out with: apt-cache show graphviz | grep Filename
+    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.20.2-8ubuntu3.2_amd64.deb' ;;
+  *)
+    echo "Buildpack error: unsupported stack: $STACK" | a
+    exit 1 ;;
+esac
+
 # Download package
 d=$(mktemp -dt XXXX)
 curl -s "$url" -o "$d"/pkg.deb
